service: import-service

custom:
  stage: dev
  webpack:
    packager: 'yarn'
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: ${self:custom.stage}
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:ListBucket'
      Resource: 'arn:aws:s3:::dmytro-shop-import-service'
    - Effect: 'Allow'
      Action: 's3:*'
      Resource: 'arn:aws:s3:::dmytro-shop-import-service/*'
    - Effect: 'Allow'
      Action: 'sqs:SendMessage'
      Resource: 'arn:aws:sqs:eu-west-1:192675374686:catalogItemsQueue'

functions:
  importProductsFile:
    handler: src/index.importProductsFile
    events:
      - http:
          path: /import
          method: GET
          authorizer:
            arn: arn:aws:lambda:eu-west-1:192675374686:function:aws-shop-authorization-service-dev-basicAuthorizer
            identitySource: method.request.header.Authorization
            type: request
  importFileParser:
    handler: src/index.importFileParser
    events:
      - s3:
          bucket: dmytro-shop-import-service
          event: s3:ObjectCreated:*
          rules:
              - prefix: uploaded
          existing: true

plugins:
  - serverless-webpack
  - serverless-offline
