service: aws-shop-backend

custom:
  stage: dev
  webpack:
    packager: 'yarn'
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
#    seed:
#      local:
#        sources:
#          - table: products
#            sources: ['./src/assets/products-only.json']
#          - table: stocks
#            sources: ['./src/assets/stocks-only.json']

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: ${self:custom.stage}

functions:
  getProductsList:
    handler: src/index.getAllProducts
    events:
      - http:
          path: /products
          method: GET
  getProductsById:
    handler: src/index.getProductById
    events:
      - http:
          path: /products/{productId}
          method: GET

resources:
  Resources:
    products:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    stocks:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: stocks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
